class EvadesData {
    static heroes = [
        "Magmax",
        "Rime",
        "Morfe",
        "Aurora",
        "Necro",
        "Brute",
        "Nexus",
        "Shade",
        "Euclid",
        "Chrono",
        "Reaper",
        "Rameses",
        "Jolt",
        "Ghoul",
        "Cent",
        "Jotunn",
        "Candy",
        "Mirage",
        "Boldrock",
        "Glob",
        "Magno",
        "Ignis",
        "Stella",
        "Viola",
        "Mortuus",
        "Cybot",
        "Echelon"
    ]

    static regions = [
        "Central Core",
        "Vicious Valley",
        "Elite Expanse",
        "Wacky Wonderland",
        "Glacial Gorge",
        "Dangerous District",
        "Peculiar Pyramid (Inner/Outer)",
        "Peculiar Pyramid Perimeter",
        "Monumental Migration (120)",
        "Humongous Hollow",
        "Haunted Halls",
        "Quiet Quarry",
        "Quiet Quarry Hard",
        "Frozen Fjord",
        "Restless Ridge",
        "Toxic Territory",
        "Magnetic Monopole",
        "Magnetic Monopole Dipoles",
        "Assorted Alcove",
        "Burning Bunker",
        "Central Core Hard",
        "Vicious Valley Hard",
        "Glacial Gorge Hard",
        "Assorted Alcove Hard",
        "Frozen Fjord Hard",
        "Toxic Territory Hard",
        "Magnetic Monopole Hard",
        "Magnetic Monopole Hard Dipoles",
        "Burning Bunker Hard",
        "Elite Expanse Hard",
        "Restless Ridge Hard",
        "Peculiar Perimeter Hard (Inner/Outer)",
        "Peculiar Perimeter Hard Perimeter",
        "Grand Garden",
        "Grand Garden Hard",
        "Ominous Occult",
        "Ominous Occult Hard",
        "Endless Echo",
        "Mysterious Mansion",
        "Dangerous District Hard",
        "Cyber Castle",
        "Catastrophic Core",
        "Endless Echo Hard",
        "Humongous Hollow Hard"
    ];
}

export default EvadesData;