class EvadesData {
    static developers = ["MiceLee", "Stovoy", "Mrnibbles", "DDBus", "PotaroNuke", "Lime", "Meldiron", "Jäckäl"];
    static headMods = ["extirpater", "Exoriz", "Jackal"];
    static seniorMods = ["Darklight", "LightY", "Raqzv", "Kaluub"];
    static mods = [
        "Gianni", "Vikenti", "Mel",
        "Amasterclasher", "basti", "Hodge",
        "Zade", "PotatoNuke", "AWEN",
        "eagle45", "Angel🌸", "Ram", "hula", "lindsay",
        "AniFonG", "MeguclOwUn", "yeetyeet47", "nosok",
    ];
    static juniorMods = [
        "jules", "waterfowlgen", "RadicalLarry", "Br1h", "зефирка",
    ];

    static staff = Array.of(...this.developers, ...this.headMods, ...this.seniorMods, ...this.mods, ...this.juniorMods);

    static heroes = [
        "Magmax",
        "Rime",
        "Morfe",
        "Aurora",
        "Necro",
        "Brute",
        "Nexus",
        "Shade",
        "Euclid",
        "Chrono",
        "Reaper",
        "Rameses",
        "Jolt",
        "Ghoul",
        "Cent",
        "Jotunn",
        "Candy",
        "Mirage",
        "Boldrock",
        "Glob",
        "Magno",
        "Ignis",
        "Stella",
        "Viola",
        "Mortuus",
        "Cybot",
        "Echelon",
        "Demona",
        "Stheno",
        "Factorb",
    ]

    static regions = [
        "Central Core",
        "Central Core Hard",
        "Catastrophic Core",
        "Vicious Valley",
        "Vicious Valley Hard",
        "Elite Expanse",
        "Elite Expanse Hard",
        "Wacky Wonderland",
        "Glacial Gorge",
        "Glacial Gorge Hard",
        "Dangerous District",
        "Dangerous District Hard",
        "Peculiar Pyramid",
        "Peculiar Pyramid Hard",
        "Stellar Square",
        "Monumental Migration",
        "Humongous Hollow",
        "Humongous Hollow Hard",
        "Haunted Halls",
        "Quiet Quarry",
        "Quiet Quarry Hard",
        "Frozen Fjord",
        "Frozen Fjord Hard",
        "Ominous Occult",
        "Ominous Occult Hard",
        "Restless Ridge",
        "Restless Ridge Hard",
        "Toxic Territory",
        "Toxic Territory Hard",
        "Magnetic Monopole",
        "Magnetic Monopole Hard",
        "Burning Bunker",
        "Burning Bunker Hard",
        "Grand Garden",
        "Grand Garden Hard",
        "Endless Echo",
        "Endless Echo Hard",
        "Mysterious Mansion",
        "Cyber Castle",
        "Cyber Castle Hard",
        "Shifting Sands",
        "Infinite Inferno",
        "Coupled Corridors",
        "Withering Wasteland",
    ]

    static regionsExtended = [
        "Central Core",
        "Vicious Valley",
        "Elite Expanse",
        "Wacky Wonderland",
        "Glacial Gorge",
        "Dangerous District",
        "Peculiar Pyramid (Inner/Outer)",
        "Peculiar Pyramid Perimeter",
        "Monumental Migration (120)",
        "Humongous Hollow",
        "Haunted Halls",
        "Quiet Quarry",
        "Quiet Quarry Hard",
        "Frozen Fjord",
        "Restless Ridge",
        "Toxic Territory",
        "Magnetic Monopole",
        "Magnetic Monopole Dipoles",
        "Burning Bunker",
        "Central Core Hard",
        "Vicious Valley Hard",
        "Glacial Gorge Hard",
        "Frozen Fjord Hard",
        "Toxic Territory Hard",
        "Magnetic Monopole Hard",
        "Magnetic Monopole Hard Dipoles",
        "Burning Bunker Hard",
        "Elite Expanse Hard",
        "Restless Ridge Hard",
        "Peculiar Perimeter Hard (Inner/Outer)",
        "Peculiar Perimeter Hard Perimeter",
        "Grand Garden",
        "Grand Garden Hard",
        "Ominous Occult",
        "Ominous Occult Hard",
        "Endless Echo",
        "Mysterious Mansion",
        "Dangerous District Hard",
        "Cyber Castle",
        "Cyber Castle Hard",
        "Catastrophic Core",
        "Endless Echo Hard",
        "Humongous Hollow Hard",
        "Shifting Sands",
        "Infinite Inferno",
        "Coupled Corridors North",
        "Coupled Corridors South",
        "Withering Wasteland",
    ];
}

export default EvadesData;